//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atm11
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtmAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AtmAccount()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int atmaccId { get; set; }
        public string AccountNumber { get; set; }
        public decimal AccountBalance { get; set; }
        public int AccTypeId { get; set; }
        public string AccUserId { get; set; }
    
        public virtual AccType AccType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
