//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atm11
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransType
    {
        public int TranstypeId { get; set; }
        public string TransType1 { get; set; }
    }
}
